import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  content: [
    './app/**/*.ts,tsx',
    './pages/**/*.ts,tsx',
    './components/**/*.ts,tsx',
    './styles/**/*.css',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'secondary-fixed': '#c9e9e1',
        'surface-dim': '#d9dadb',
        'surface-tint': '#006b5e',
        'tertiary-fixed': '#ffdbd0',
        'on-background': '#191c1d',
        'primary-container': '#006b5e',
        secondary: '#46645e',
        'on-tertiary-fixed-variant': '#723521',
        'on-primary-container': '#95e8d8',
        'inverse-primary': '#83d5c5',
        'inverse-on-surface': '#f0f1f2',
        'primary-fixed': '#9ff2e1',
        'on-surface': '#191c1d',
        'outline-variant': '#bec9c5',
        'inverse-surface': '#2e3132',
        tertiary: '#723521',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-primary-fixed': '#00201b',
        'tertiary-fixed-dim': '#ffb59e',
        'secondary-container': '#c6e7de',
        'on-secondary-fixed-variant': '#2f4c46',
        'on-error': '#ffffff',
        primary: '#005147',
        'on-secondary-container': '#4b6862',
        'surface-variant': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#390b00',
        'on-secondary-fixed': '#01201b',
        'on-secondary': '#ffffff',
        outline: '#6e7976',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'tertiary-container': '#8f4c36',
        'surface-container': '#edeeef',
        'surface-bright': '#f8f9fa',
        'on-primary': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'secondary-fixed-dim': '#adcdc5',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#3e4946',
        surface: '#f8f9fa',
        'on-tertiary-container': '#ffcebf',
        'on-primary-fixed-variant': '#005046',
        background: '#f8f9fa',
        'primary-fixed-dim': '#83d5c5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        'xxl': '1.5rem',
        full: '9999px',
        '2xl': '1.5rem',
      },
      boxShadow: {
        'ambient': '0 20px 40px rgba(25, 28, 29, 0.06)'
      },
      fontFamily: {
        headline: ['Manrope', 'ui-sans-serif', 'system-ui'],
        body: ['Inter', 'ui-sans-serif', 'system-ui'],
        label: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config
