import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'

export default {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-variant': '#e1e3e4',
        'surface-bright': '#f8f9fa',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'error-container': '#ffdad6',
        'primary': '#005147',
        'primary-container': '#006b5e',
        'primary-fixed': '#9ff2e1',
        'primary-fixed-dim': '#83d5c5',
        'inverse-primary': '#83d5c5',
        'on-surface': '#191c1d',
        'on-background': '#191c1d',
        'on-surface-variant': '#3e4946',
        'on-primary': '#ffffff',
        'on-primary-container': '#95e8d8',
        'on-primary-fixed': '#00201b',
        'on-primary-fixed-variant': '#005046',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4b6862',
        'secondary': '#46645e',
        'secondary-container': '#c6e7de',
        'secondary-fixed': '#c9e9e1',
        'secondary-fixed-dim': '#adcdc5',
        'on-secondary-fixed': '#01201b',
        'on-secondary-fixed-variant': '#2f4c46',
        'tertiary': '#723521',
        'tertiary-container': '#8f4c36',
        'tertiary-fixed': '#ffdbd0',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffcebf',
        'on-tertiary-fixed': '#390b00',
        'on-tertiary-fixed-variant': '#723521',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#6e7976',
        'outline-variant': '#bec9c5',
      },
      borderRadius: {
        xl: '1.5rem',
        md: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 20px 40px rgba(25, 28, 29, 0.06)',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [forms],
} satisfies Config
